# gspm project.yml <https://gs-project-manager-docs.readthedocs.io/en/latest/schema.html>
name: godot-ecs-rts
path: .
version: 0.0.0
default_type: git
author: Rasmus Vermeulen
email: rasmus_vermeulen@tutanota.com
twitter:
copyright: Copyright 2020
license:
godot:
  local: $godot_324rc$

project:
  url: none

assets:
  todo-manager:
    location: https://github.com/OrigamiDev-Pete/TODO_Manager
    branch: v1.1
    includes:
      - dir: addons/Todo_Manager

  gut:
    location: https://github.com/bitwes/Gut.git
    includes:
      - dir: addons/gut

  gs-ecs:
    location: https://gitlab.com/godot-stuff/gs-ecs.git
    branch: 3.2
    includes:
      - dir: addons/gs_ecs

  gs-logger:
    location: https://gitlab.com/godot-stuff/gs-logger.git
    branch: 3.2
    includes:
      - dir: addons/gs_logger

  # godot-next:
  #   location: https://github.com/willnationsdev/godot-next.git
  #   branch: master
  #   includes:
  #     - dir: addons/godot-next

  # metadata-inspector:
  #   location: https://github.com/ballerburg9005/godot-metadata-inspector.git
  #   branch: master
  #   includes:
  #     - dir: addons/metadata_inspector

  # godot-plugin-refresher:
  #   location: https://github.com/godot-extended-libraries/godot-plugin-refresher.git
  #   branch: master
  #   includes:
  #     - dir: addons/godot-plugin-refresher

pre_install:

post_install:

pre_build:

post_build:
